version = "1.0"

[metadata]
author_name = "Kaiser Sun"
author_email = "hsun74@jhu.edu"
difficulty = "medium"
category = "document-generation"
tags = ["markdown", "mdx", "fumadocs", "format-conversion"]
data_source = "Directly taken from existing real-world open source md files. Current using the CONTRIUTING.md in SkillsBench, but can be swapped for any .md files for testing."

[verifier]
timeout_sec = 300.0

[agent]
timeout_sec = 600.0

[environment]
build_timeout_sec = 300.0
cpus = 1
memory_mb = 2048
storage_mb = 5120
