version = "1.0"

[metadata]
author_name = "Kaiser Sun"
author_email = "hsun74@jhu.edu"
difficulty = "medium"
category = "software-development"
tags = [ "software-development", "excel", "open-source", "audit"]

[verifier]
timeout_sec = 900.0

[agent]
timeout_sec = 900.0

[environment]
build_timeout_sec = 600.0
cpus = 1
memory_mb = 4096
storage_mb = 10240
allow_internet = true